export const catalogos = [
    {
        "classe":"automacaoeletrica",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/Kuettner_Automation.pdf",
        "titulo":"Automação e engenharia elétrica: soluções para plantas industriais",
        "tag":"Automação e Elétrica",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/Kuttner_cat_en_peneiramento.pdf",
        "titulo":"Sistemas de peneiramento",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_en_separadores_magneticos.pdf",
        "titulo":"Separadores magnéticos",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_en_alimentadores_vibratorios.pdf",
        "titulo":"Alimentadores vibratórios",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/allair.pdf",
        "titulo":"ALLAIR®",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/allflux.pdf",
        "titulo":"ALLFLUX®",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/ccc.pdf",
        "titulo":"xxx",
        "tag":"Mineração",
    },
    {
        "classe":"mineracao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/alljig.pdf",
        "titulo":"ALLJIG®",
        "tag":"Mineração",
    },
    {
        "classe":"fundicao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_cubilo.pdf",
        "titulo":"Tecnologia para fusão com cubilô",
        "tag":"Fundição",
    },
    {
        "classe":"fundicao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_resfriador.pdf",
        "titulo":"Resfriador de leito fluidizado",
        "tag":"Fundição",
    },
    {
        "classe":"fundicao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_misturador.pdf",
        "titulo":"Misturador de areia Speedmullor",
        "tag":"Fundição",
    },
    {
        "classe":"fundicao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/catalogo knbs.pdf",
        "titulo":"Kuttner No-Bake Solutions",
        "tag":"Fundição",
    },
    {
        "classe":"fundicao",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_fundicao.pdf",
        "titulo":"Tecnologias para fundição",
        "tag":"Fundição",
    },
    {
        "classe":"meioambiente",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_luehr_filter_geral.pdf",
        "titulo":"Sistemas para o controle da qualidade do ar da LUEHR FILTER",
        "tag":"Meio Ambiente",
    },
    {
        "classe":"meioambiente",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_despoeiramento.pdf",
        "titulo":"Sistemas de despoeiramento para alto-forno, aciaria e fundição",
        "tag":"Meio Ambiente",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/Kuettner_shaft.pdf",
        "titulo":"Tecnologias OXYCUP® para reciclagem de resíduos siderúrgicos",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/Kuettner_Cokemaking.pdf",
        "titulo":"Equipamentos para coqueria",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_recuperacao_calor.pdf",
        "titulo":"Recuperação de calor em processos industriais",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/Kuettner_PCI.pdf",
        "titulo":"PCI - Injeção de finos de carvão no alto-fornos",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_despoeiramento.pdf",
        "titulo":"Sistemas de despoeiramento para alto-forno, aciaria e fundição",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_trat_ferro_aco.pdf",
        "titulo":"Tratamento de ferro e aço",
        "tag":"Siderurgia",
    },
    {
        "classe":"siderurgia",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_cat_pt_beneficiamento_mat_prima.pdf",
        "titulo":"Beneficiamento de matérias-primas na indústria siderúrgica",
        "tag":"Siderurgia",
    },
    {
        "classe":"tecnologiaskuttner",
        "imagem":"imgs/catalogos/catalogo.png",
        "arquivo":"docs/catalogos/kuttner_catalogo_geral.pdf",
        "titulo":"Catálogo Geral",
        "tag":"Tecnologias Kuttner",
    }
]


